CREATE TABLE IF NOT EXISTS mods (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  metadata TEXT,
  status BIT NOT NULL,
  installed_on TIMESTAMPTZ NOT NULL,
  updated_on TIMESTAMPTZ NOT NULL,
  creator_id BIGINT NOT NULL REFERENCES creators (id)
);

CREATE TABLE IF NOT EXISTS creators (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL
);
